### ISSUE TITLE
Add support for all Watson Services

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/dotnet-standard-sdk#1]
This should be converted into an epic with an issue for each of the services (these are the important ones for now)
- [x] Conversation
- [x] Discovery
- [x] Speech to Text
- [x] Text to Speech
- [x] Visual Recognition
- [x] Language Translator
- [x] Personality Insights
- [x] Tone Analyzer
- [x] Natural Language Understanding

The following are either deprecated, low priority or will be changing soon:
- [ ] Document Conversion
- [ ] Natural Language Classifier
- [ ] Retrieve and Rank
- [ ] Alchemy Data News
- [ ] Tradeoff Analytics

**Comment by mediumTaj** [comment]
I created a spreadsheet showing what has been supported sofar. If you would like write access please message me with your email.

https://docs.google.com/spreadsheets/d/12FZ2kVh1TNDGGgAYY0sEBx0ueKVKNooeGXINba0SsBo/edit?usp=sharing

**Comment by germanattanasio** [comment]
This was completed
