### ISSUE TITLE
Natural Language Understanding Service

### ISSUE THREAD

**Issue by shawnmclean** [watson-developer-cloud/dotnet-standard-sdk#102]
Are there any plans to implement the NLU services? I do not see it listed in: https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/1

I could start working iteratively on this package if nothing is planned.

**Comment by mediumTaj** [comment]
Thanks for your help!! NLU is definitely planned. I am currently working on auto generating the service abstractions through swagger code gen. We do need help on the sdk core and services that are not easily generated like speech to text and text to speech.

**Comment by shawnmclean** [comment]
@mediumTaj Got any ETA for NLU?

**Comment by mediumTaj** [comment]
No ETA yet. I'm planning to start generation of NLU and Discovery this week. You can track the generated SDK [here](https://github.com/mediumTaj/dotnet-standard-sdk-generated). Don't mind the readme files. I haven't had time to work on those templates yet.
