### ISSUE TITLE
[discovery] Abstract Discovery service. 

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/dotnet-standard-sdk#11]
Abstract the `Discovery` service into the `dotnet-standard-sdk`
- [ ] Abstract service
- [ ] Add inline documentation
- [ ] Add service examples to readme
- [ ] Add unit tests
- [ ] Add integration tests

**Comment by mediumTaj** [comment]
Hey @maykonsIBM are you abstracting this service?

**Comment by maykonsIBM** [comment]
@mediumTaj Slower than I'd like, but, yes I'm doing abstraction

**Comment by mediumTaj** [comment]
Ok thanks! I just finished visual recogniton so if you need help with this you I can do some work on it too. At lest start writing tests. Let me know! For now I will start writing tests for conversation and making sure we are at a good point with the other services. Thanks for your help!
