### ISSUE TITLE
Implement retry functionality in .NET SDK integration tests

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/dotnet-standard-sdk#113]
We need integration tests to retry on service failure.

**Comment by mediumTaj** [comment]
@atilatosta I can't find any kind of attribute in visual studio test tools. Is this something we need to implement ourselves or do you know of something built into the test runner?

**Comment by atilatosta** [comment]
@mediumTaj I believe there is no such feature. We will have to develop. I'll search.

**Comment by mediumTaj** [comment]
Ok - if we have to develop this feature, let's figure out the best way to implement so we can use for any test!

**Comment by mediumTaj** [comment]
Still nothing in the testing framework

**Comment by mediumTaj** [comment]
Closing as nothing available in testing framework
