### ISSUE TITLE
Support authentication tokens

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/dotnet-standard-sdk#119]
Support tokens for authentication in addition to local file/env variable

https://www.ibm.com/watson/developercloud/doc/common/getting-started-tokens.html

**Comment by atilatosta** [comment]
@mediumTaj Is this defect related to this other #116 ?

**Comment by mediumTaj** [comment]
Ah yes sorry this is a duplicate then. I will be working on the same thing for the Unity SDK.
