### ISSUE TITLE
[speech-to-text] Abstract Speech to Text service. 

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/dotnet-standard-sdk#12]
Abstract the `Speech to Text` service into the `dotnet-standard-sdk`
- [ ] Abstract service
- [ ] Add inline documentation
- [ ] Add service examples to readme
- [ ] Add unit tests
- [ ] Add integration tests

**Comment by atilatosta** [comment]
Some tasks that I need to do:
- [ ] remove builder pattern from STT;
- [ ] remove obsolete classes;
