### ISSUE TITLE
Cannot install Visual Recognition API

### ISSUE THREAD

**Issue by cheawan** [watson-developer-cloud/dotnet-standard-sdk#121]
PM> Install-Package IBM.WatsonDeveloperCloud.VisualRecognition.v3
  GET https://api.nuget.org/v3/registration2-gz/ibm.watsondevelopercloud.visualrecognition.v3/index.json
  OK https://api.nuget.org/v3/registration2-gz/ibm.watsondevelopercloud.visualrecognition.v3/index.json 236ms
Restoring packages for c:\users\teocw\documents\visual studio 2017\Projects\WebApplication1\WebApplication1\WebApplication1.csproj...
Install-Package : Package Microsoft.AspNet.WebApi.Client 5.2.3 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.AspNet.WebApi.Client 5.2.3 supports:
  - net45 (.NETFramework,Version=v4.5)
  - portable-net45+netcore45+wp8+wp81+wpa81 (.NETPortable,Version=v0.0,Profile=wp8+netcore45+net45+wp81+wpa81)
At line:1 char:1
+ Install-Package IBM.WatsonDeveloperCloud.VisualRecognition.v3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package System.Runtime.Serialization.Json 4.0.1 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package System.Runtime.Serialization.Json 4.0.1 supports:
  - dnxcore50 (DNXCore,Version=v5.0)
  - dotnet5.1 (.NETPlatform,Version=v5.1)
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcore50 (.NETCore,Version=v5.0)
  - win8 (Windows,Version=v8.0)
  - wp8 (WindowsPhone,Version=v8.0)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
At line:1 char:1
+ Install-Package IBM.WatsonDeveloperCloud.VisualRecognition.v3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with .NETCoreApp,Version=v1.1.
At line:1 char:1
+ Install-Package IBM.WatsonDeveloperCloud.VisualRecognition.v3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'WebApplication1'.
At line:1 char:1
+ Install-Package IBM.WatsonDeveloperCloud.VisualRecognition.v3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by cheawan** [comment]
Can someone please advise how to install the package?

**Comment by atilatosta** [comment]
@cheawan hi! soon will be available a new version [(1.1.0)](https://github.com/watson-developer-cloud/dotnet-standard-sdk/milestone/3) that will fix this problem.

**Comment by cheawan** [comment]
Great! May i know when is the date?

**Comment by atilatosta** [comment]
@cheawan the due date is June 30, [see here (1.1.0)](https://github.com/watson-developer-cloud/dotnet-standard-sdk/milestone/3)

**Comment by cheawan** [comment]
@atilatosta looking forward to the new release :)

**Comment by atilatosta** [comment]
@cheawan sorry! usually making the releases is the Taj and with the holiday of July 4th, I believe he will only return tomorrow.

**Comment by atilatosta** [comment]
@cheawan tonight, the version 1.1.0 was released. Tks!
