### ISSUE TITLE
[NaturalLanguageUnderstanding.v1] Could not load file or assembly - System.Net.Http.Formatting

### ISSUE THREAD

**Issue by ratans** [watson-developer-cloud/dotnet-standard-sdk#125]
While using the nuget package - IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1, and creating an object of new NaturalLanguageUnderstandingService(); I am facing this issue -

`System.IO.FileLoadException: 'Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'`

There is no 5.2.4.0 version of System.Net.Http.Formatting available. Please let us know if you are working on this fix.

**Comment by mediumTaj** [comment]
See this issue here
https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/118
