### ISSUE TITLE
[general] Change exception handling to throw more specific exception

### ISSUE THREAD

**Issue by atilatosta** [watson-developer-cloud/dotnet-standard-sdk#128]
We neeed change the code gen to the exception handling to throw more specific exception ([ServiceResponseException](https://github.com/watson-developer-cloud/dotnet-standard-sdk/blob/development/src/IBM.WatsonDeveloperCloud/Http/Exceptions/ServiceResponseException.cs))

**Comment by mediumTaj** [comment]
Will change in Codegen

**Comment by mediumTaj** [comment]
I think this is complete
