### ISSUE TITLE
[Conversation]ServiceResponseException: The API query failed with status code 

### ISSUE THREAD

**Issue by AmenehSh** [watson-developer-cloud/dotnet-standard-sdk#131]
I'm trying to connect to a conversation workspace that I created with my Bluemix account. I'm running a similar code to what is provided in conversation example (ConversationServiceExample.cs). I get the error below when the "message" function is called (

_conversation = new ConversationService("my username", "my password", ConversationService.CONVERSATION_VERSION_DATE_2017_05_26);
            _workspaceID = "my workspace id";
var result = _conversation.Message(_workspaceID, messageRequest);)

Error: 
System.AggregateException: 'One or more errors occurred.'
Inner Exception
ServiceResponseException: The API query failed with status code NotFound: Not Found

Does anyone know how I should resolve this?

**Comment by mediumTaj** [comment]
You need to create a MessageRequest to send.

```
MessageRequest messageRequest = new MessageRequest()
{
    Input = new InputData()
        {
            Text = "test text";
        }
}
```

**Comment by AmenehSh** [comment]
I already did. Just didn't paste the whole file. 
...
```
 MessageRequest messageRequest = new MessageRequest()
            {
                Input = new InputData()
                {
                    Text = _inputString
                },
                AlternateIntents = true
            };

            Console.WriteLine(string.Format("\nCalling Message(\"{0}\")...", _inputString));
            var result = _conversation.Message(_workspaceID, messageRequest);
```

**Comment by mediumTaj** [comment]
It looks correct, are you sure the username and password are correct when instantiating the service? I am currently updating the Conversation service abstraction to make some properties in MessageRequest and MessageResponse dynamic.

**Comment by AmenehSh** [comment]
Sorry, you are right. I did a mistake while copy pasting my username and password. now it works fine. thanks. I will delete this issue.
