### ISSUE TITLE
[conversation] GetWorkspace() problem sending export parameter

### ISSUE THREAD

**Issue by atilatosta** [watson-developer-cloud/dotnet-standard-sdk#140]
When trying to execute this code the intentions, entities and etc are not returned:

```c#
IConversationService _conversationSerivce =
    new ConversationService("<username>", "<password>", ConversationService.CONVERSATION_VERSION_DATE_2017_05_26);

WorkspaceExportResponse workspace =
    _conversationSerivce.GetWorkspace("cb12404f-c506-4502-9a6c-da351f3e8a57", true);
```
The error occurs because the "export" parameter sent in the querystring is going like camelcase.

**Comment by atilatosta** [comment]
Fixed: changed the UriExtension class, to ensure that the parameters sent are in lowercase.

**Comment by savethehousemouse** [comment]
So how can I get the 1.3 prerelease with the problem fixed?

**Comment by savethehousemouse** [comment]
nuget does not offer -as I understand- to load anything other than 'stable'

**Comment by mediumTaj** [comment]
@savethehousemouse Sorry, we were waiting on some other issues to get resolved in the SDK core before putting out a new release. @atilatosta Is there a workaround to get this in?
