### ISSUE TITLE
[Natural Language Understanding] IOException & HttpRequestException

### ISSUE THREAD

**Issue by RavGup** [watson-developer-cloud/dotnet-standard-sdk#143]
I downloaded Mircosoft Studio with Core Framework.
Installed IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1
Write below sample code to call to get the sentiment analysis.
`NaturalLanguageUnderstandingService _nls = new NaturalLanguageUnderstandingService();
            _nls.VersionDate = "NATURAL_LANGUAGE_UNDERSTANDING_VERSION_DATE_2017_02_27";
            _nls.SetCredential("*****-***UserName***-**************", "**Password***");
            Parameters param = new Parameters()
            {
                Text = "This is very good news!!",
                Features = new Features()
                {
                    Keywords = new KeywordsOptions()
                    {
                        Limit = 8,
                        Sentiment = true,
                        Emotion = true
                    }
                }
            };

            var result = _nls.Analyze(param);
            Console.WriteLine(result);
            Console.ReadLine();`
I am getting below error :
IOException: Unable to read data from the transport connection. The connection was closed before all data could be read. Expected 4335 bytes, read 0 bytes.
Source : System.Private.CoreLib
Stack Trace :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.StreamToStreamCopy.<CopyAsyncToPreSizedLimitMemoryStream>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__48.MoveNext()

**Please note:** I am accessing this application behind Corporate proxy.
**Thing to note here**. below GET request from browser giving me expected output.
`https://watson-api-explorer.mybluemix.net/natural-language-understanding/api/v1/analyze?version=2017-02-27&url=http%3A%2F%2Fmoney.cnn.com%2F2017%2F08%2F01%2Ftechnology%2Fbusiness%2Fbitcoin-cash-new-currency%2Findex.html&features=sentiment&return_analyzed_text=false&clean=true&fallback_to_raw=true&concepts.limit=8&emotion.document=true&entities.limit=50&entities.emotion=false&entities.sentiment=false&keywords.limit=50&keywords.emotion=false&keywords.sentiment=false&relations.model=en-news&semantic_roles.limit=50&semantic_roles.entities=false&semantic_roles.keywords=false&sentiment.document=true`

**Comment by atilatosta** [comment]
@RavGup there is a issue (#117) related to this. I will put it in the roadmap.

**Comment by mediumTaj** [comment]
Is this still an issue?
