### ISSUE TITLE
[Conversation] Escape input string for DeleteCounterExample

### ISSUE THREAD

**Issue by rafarpd** [watson-developer-cloud/dotnet-standard-sdk#144]
I can list and create, but cannot delete a counterexample:

-----------------
The API query failed with status code NotFound: Not Found

Descrição: Ocorreu uma exceção sem tratamento durante a execução da atual solicitação da Web. Examine o rastreamento de pilha para obter mais informações sobre o erro e onde foi originado no código. 

Detalhes da Exceção: IBM.WatsonDeveloperCloud.Http.Exceptions.ServiceResponseException: The API query failed with status code NotFound: Not Found

Erro de Origem: 

Linha 102:        string exampleToDelete = "what's your name?";
Linha 103:        ConversationService _conversation = new ConversationService(user, password, ConversationService.CONVERSATION_VERSION_DATE_2017_05_26);
Linha 104:        var result = _conversation.DeleteCounterexample(workspaceId, exampleToDelete);

**Comment by atilatosta** [comment]
@rafarpd please make sure that the workspace id is correct according with the credentials

**Comment by atilatosta** [comment]
When deleting the example, the text is sent in the path of the url, and as it is with the question mark, we are not doing the encoding correctly

**Comment by mediumTaj** [comment]
Currently since we are generating the code for this abstraction we cannot escape the string because we get the `path` from swagger documentation and I cannot think of a good way to escape this. Let me bring this up with the generation team.

**Comment by mediumTaj** [comment]
Adding this to planning
