### ISSUE TITLE
[Conversation] - Dialog Node methods with wrong enpoint

### ISSUE THREAD

**Issue by atilatosta** [watson-developer-cloud/dotnet-standard-sdk#150]
the methods are with the wrong url, it has "dialogNodes" and should be "dialog_nodes":

ConversationService.DeleteDialogNode
ConversationService.GetDialogNode
ConversationService.UpdateDialogNode

**Comment by mediumTaj** [comment]
@atilatosta Sorry, I will fix this in the codegen! If you can fix this when you have some time in the development branch, that would be awesome!

**Comment by mediumTaj** [comment]
This should be fixed.
