### ISSUE TITLE
[speech-to-text] Websocket API Support

### ISSUE THREAD

**Issue by RMichaelPickering** [watson-developer-cloud/dotnet-standard-sdk#153]
As far as I can tell, the Watson Speech to Text service has a Websocket API available but this has not yet been included in the .NET SDK. It is desperately needed!

**Comment by mediumTaj** [comment]
@atilatosta Do you still have the streaming example you built?

**Comment by mediumTaj** [comment]
From @RMichaelPickering in another issue to consolidate.

>Already opened an issue requesting Websocket API support but am open to other options. What is the recommended leading practice for transcribing live, streaming audio using the Watson Speech To Text service and the .NET SDK? My requirement is, ideally, to be able to stream audio for transcription by Watson STT from a Windows 10 client machine running a UWP app developed in C# and .NET, but a console app developed in any Microsoft-supported language would be a reasonable compromise.
>
>I believe that this is the only IBM-supported SDK for Windows and .NET, correct? It doesn't seem to have been explicitly stated but so far as I can tell, the only IBM-supported language for .NET is C#, correct?
>
>In case I've missed them, are there any existing examples of live audio streaming with the Watson .NET SDK?

**Comment by mediumTaj** [comment]
Still want to do this... possibly after async is implemented

**Comment by RMichaelPickering** [comment]
@mediumTaj I still think that Websocket support is critical for any use case of Watson STT and thus should be available in all Watson SDKs. Having said this, we've moved on to using node.js as a middle tier, and thus don't really require .NET support any more. On the other hand, the Watson STT Websocket itself doesn't actually seem to be working properly from our node.js app running in IBM Cloud, and we've had an issue open for this for four months now...

**Comment by RMichaelPickering** [comment]
Has async been implemented?

**Comment by mediumTaj** [comment]
Not yet

**Comment by mediumTaj** [comment]
Still active
