### ISSUE TITLE
 Add `X-Global-Transaction-Id` as part of the error

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/dotnet-standard-sdk#162]
If the SDK returns an error add the `X-Global-Transaction-Id` response header to the response.

**Comment by germanattanasio** [comment]
Taj I think this was important to debug issues, did you get the change to look at it?

**Comment by mediumTaj** [comment]
Let me take a look at it this week. I have this in the response headers. Shouldn’t be too much trouble to add to the error

**Comment by mediumTaj** [comment]
https://github.com/watson-developer-cloud/dotnet-standard-sdk/pull/301
