### ISSUE TITLE
[visual-recognition] - Problem to classify with custom classifier

### ISSUE THREAD

**Issue by Mayco-Anderson** [watson-developer-cloud/dotnet-standard-sdk#163]
I am trying to classify an image using my own trained classifier.

I am passing the classifier Id into the parameters, but it is always using the default classifier.
I already validated the parameters on the api explorer and the parameters are correct.

It seems like a bug, not sure if this is the right place to discuss this.

**Comment by mediumTaj** [comment]
Can you post your code calling Visual Recognition?

**Comment by Mayco-Anderson** [comment]
Sure, here is the piece of code where i call the classify

` var classifierResult = _visualRecognition.Classify(image, fileName, "image/jpeg", classifierIDs: _classifierId, threshold: 0.1f);`

The classifier id is: 

`        private readonly string[] _classifierId =  { "M*********96" };
`

When I retrieve the classifiers with `_visualRecognition.GetClassifiersBrief();` My classifier is successfully retrieved.

**Comment by mediumTaj** [comment]
Parameter names were missing from the classify method. I added them in. If you would like to test it out the PR is [here](https://github.com/watson-developer-cloud/dotnet-standard-sdk/pull/164). I will be doing a few more updates this week and next before pushing a release.

**Comment by mediumTaj** [comment]
Merged into develop to be included in next release.

**Comment by Mayco-Anderson** [comment]
Thank you for the quick responses and fix =D

**Comment by hkbhkb7** [comment]
I am also facing same issue. Please help to solve this problem because I have urgent business requirement
