### ISSUE TITLE
[Visual Recognition]_visualRecognition.Classify(imageByte, "Image.jpg", "image/jpg", Urls, Classifiers,null,0.5f); is not returning proper data 

### ISSUE THREAD

**Issue by HanumantappaBudihal** [watson-developer-cloud/dotnet-standard-sdk#165]
I am trying to classify an image using my own trained classifier. Same line code was returning proper data before a week but same code is not working properly.
I am passing the classifier Id into the parameters, but it is always using the default classifier.

**Comment by hkbhkb7** [comment]
I am developing VR tool in .NET framework. _visualRecognition. Classify () this method was working fine for custom classifiers before a week. Now it's not classifying any images. It's working as default classify method even I passed classifierID's and Owner Id's. I want to resolve this problem as soon as possible

**Comment by mediumTaj** [comment]
Please try to use the development branch for now. There were some API changes to the service and we are planning a release of the SDK next week.

**Comment by hkbwork** [comment]
I would like to know about .NET SDK update, still I am facing same problem

**Comment by hkbhkb7** [comment]
I would like to know about the new .NET SDK release. Still, I am facing same problem with the "Classify Method". It would very help if it's solved as soon as possible because I have a urgent requirement.

**Comment by mediumTaj** [comment]
@hkbhkb7 is the develop branch not working for you?

**Comment by HanumantappaBudihal** [comment]
Yes , It's now working for even development branch.
