### ISSUE TITLE
[document-conversion] Abstract Document Conversion service. 

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/dotnet-standard-sdk#18]
Abstract the `Document Conversion` service into the `dotnet-standard-sdk`
- [ ] Abstract service
- [ ] Add inline documentation
- [ ] Add service examples to readme
- [ ] Add unit tests
- [ ] Add integration tests

**Comment by caiosm1005** [comment]
I am very interested in using the Document Conversion API from within a .NET plugin.

**Comment by germanattanasio** [comment]
Document Conversion was deprecated and all its capabilities are not part of discovery. I'm closing this since Discovery is already supported in this SDK
