### ISSUE TITLE
Error		Could not install package 'IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1.Temp 0.2.0'.

### ISSUE THREAD

**Issue by mrHassanRaza** [watson-developer-cloud/dotnet-standard-sdk#188]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1.Temp 0.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by mediumTaj** [comment]
This is not our package. Please use IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1
