### ISSUE TITLE
[Text-To-Speech]

### ISSUE THREAD

**Issue by parsha** [watson-developer-cloud/dotnet-standard-sdk#189]
It seems that the synthesize method in the new update does not produce current Stream.

I was using the last version and it was working properly but today I updated to the new release (2.0.0) and it seems it's broken.

I used
```
Text synthesizeText = new Text
            {
                _Text = text
            };
Stream ttsStream = ttsService.Synthesize(synthesizeText, "audio/wav", "en-GB_KateVoice");
```

But when I play the content of the stream, it is almost empty.

I have tried all the "accept" options or other model voices...

**Comment by mediumTaj** [comment]
Let me take a look.

**Comment by mediumTaj** [comment]
Hi @parsha - in `src/IBM.WatsonDeveloperCloud.TextToSpeech.v1/TextToSpeechService.cs` can you change line 128

from:
```
request.WithHeader("Accept", accept);
```

to (mind the case of the `accept`): 
```
request.WithArgument("accept", accept);
```

If you are using the nuget package, I will have an update to the package today.

**Comment by mediumTaj** [comment]
@parsha IBM.WatsonDeveloperCloud.TextToSpeech.v1 v2.0.1 has been deployed to NuGet and will be available shortly.
