### ISSUE TITLE
[Natural Language Understanding] Update documentation

### ISSUE THREAD

**Issue by pierre-weceipt** [watson-developer-cloud/dotnet-standard-sdk#194]
The quick sample provided  [here](https://github.com/watson-developer-cloud/dotnet-standard-sdk/tree/development/src/IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1) is incorrect.

```c#
// create a Natural Language Understanding Service instance
NaturalLanguageUnderstandingService _naturalLanguageUnderstandingService = new NaturalLanguageUnderstandingService();

// set the credentials
_naturalLanguageUnderstandingService.SetCredential();
```
should be 
```c#
// create a Natural Language Understanding Service instance
NaturalLanguageUnderstandingService _naturalLanguageUnderstandingService = new NaturalLanguageUnderstandingService("<username>", "<password>", "2017-02-27");
```

It would help others getting started, I had to look at unit testing code to find the correct version string and avoid the error message `BadRequest`. Maybe the API exception messages could also be more explicit.

**Comment by mediumTaj** [comment]
Thanks! fixed in this readme and others https://github.com/watson-developer-cloud/dotnet-standard-sdk/pull/195
