### ISSUE TITLE
[Natural-Language-Understanding] unauthorized error when using .Net SDK for Natural Language Understanding

### ISSUE THREAD

**Issue by newtogithub2** [watson-developer-cloud/dotnet-standard-sdk#196]
I am trying to use the .Net SDK for Natural Language Understanding, but I keep getting an "unauthorized" error.

I tried various forms of the code below but I can't get anything to work.  The code below is basically from the SDK example code.  I have registered the ID and password and have successfully created a free account on the Watson cloud. So I am not sure what else do I need to do.
```
NaturalLanguageUnderstandingService _naturalLanguageUnderstandingService  = new NaturalLanguageUnderstandingService(username, password, "2017-02-27");

_naturalLanguageUnderstandingService.Endpoint = "https://gateway.watsonplatform.net/natural-language-understanding/api/v1/analyze?version=2017-02-27";
```
        Parameters parameters = new Parameters()
         {
             Text = "This 55 year old man with known coronary artery disease comes for a follow-up visit today.",
             Features = new Features()
             {
                 Keywords = new KeywordsOptions()
                 {
                     Limit = 8,
                     Sentiment = true,
                     Emotion = true
                 }
             }
         };
         var result = _naturalLanguageUnderstandingService.Analyze(parameters);

**Comment by newtogithub2** [comment]
**mediumTaj** thank you very much for your prompt response. That was very nice of you.

Unfortunately, when I try to you use your URL I still get the following error in my C# code:
"The API query failed with status code Unauthorized: Unauthorized"

Were you able to get the example in the SDK to work? The interesting thing is, even when I run the API sample page on the Watson site... https://watson-api-explorer.mybluemix.net/apis/natural-language-understanding-v1#!/Analyze/analyze   The POST section only works if I leave the ID/PWD **blank** at the top of the page. If I try to run that page with my ID/PWD, I keep getting prompted to re-enter my password.

I know my ID/PWD is working because if I try to login into the IBM cloud I am able to get in and view their "dashboard" page.  So I am not sure how to proceed from here.  Am I supposed to use a different ID/PWD? I am trying to run a demo in a few days with IBM's natural language processing but this "unauthorized" error is a complete roadblock at this time for me.

**Comment by newtogithub2** [comment]
I keep getting the "unauthorized" error even with that URL?


See my feedback, at this GitHub link:  https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/196

[https://avatars1.githubusercontent.com/u/37812566?s=400&v=4]<https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/196>

[Natural-Language-Understanding] unauthorized error when using .Net SDK for Natural Language Understanding · Issue #196 · watson-developer-cloud/dotnet-standard-sdk<https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/196>
github.com
I am trying to use the .Net SDK for Natural Language Understanding, but I keep getting an "unauthorized" error. I tried various forms of the code below but I can't get anything to wor...





________________________________

**Comment by mediumTaj** [comment]
The SDK integration tests and examples are working. Can you double check your credentials?

**Comment by newtogithub2** [comment]
**mediumTaj**  thanks again for your response.  I did try without setting the endpoint, but I got same error.   

Also, I don't know how else to verify my credentials other than logging into the IBM cloud (which works).  I think my account is just a "Lite" account.  Are people with "Lite" accounts able to use this SDK?  Is there another way of checking if my credentials are valid for SDK usage?

**Comment by mediumTaj** [comment]
Can you please send me your code including credentials to ajiemar at gmail dot Com

**Comment by mediumTaj** [comment]
@newtogithub2 I see what is happening. You are using your IBM Cloud credentials to try to authenticate the service. You need to go into your IBM Cloud Natural Language Understanding service (console.bluemix.net and click on your Natural Language Understanding instance) click **Service Credentials** on the right, you should see your credentials for the service. If they are not there, click the **New Credential** button. Click **View credentials** to access your service credentials. These are the credentials you need to instantiate the service.

**Comment by mediumTaj** [comment]
@newtogithub2 Were you able to make this work?

**Comment by newtogithub2** [comment]
@mediumTaj - yep, you were absolutely right!!  Once I did that everything fell in place. I even stumbled upon this very helpful link https://console.bluemix.net/docs/services/natural-language-understanding/getting-started.html while following your directions. It has a nice "getting started tutorial" section.  Thank you so much for being so helpful with such quick responses. I would not be where I am now on this project without your help!

**Comment by mediumTaj** [comment]
Awesome, glad to hear. Closing this issue.
