### ISSUE TITLE
[Visual Recognition] Image extension is not specified 

### ISSUE THREAD

**Issue by MrIceWolf** [watson-developer-cloud/dotnet-standard-sdk#197]
There seems to be an issue at line 165 of 
`src/IBM.WatsonDeveloperCloud.VisualRecognition.v3/VisualRecognitionService.cs` 
in DetectFaces() causing it to only return errors when uploading images from a local disk.

The line in question is:

`formData.Add(imagesFileContent, "images_file", "filename");`

The third parameter `"filename"` looks like it should be `''filename.jpg''` or `''filename.png''` or the file extension should be specified elsewhere before sending the formData.

I encountered the issue by using
`_visualRecogntionService.DetectFaces( <System.IO.Stream of my image>, null, "image/jpeg");`
and inspecting the contents of the returned DetectedFaces class after no results showed up.

The Images[] array in this class only contained an error which said:
`Ignoring non-image or unsupported extension (filename)`

This shows that the file extension is not specified before the API call is being made since the ignored file `filename` has no extension.

**Comment by mediumTaj** [comment]
Fixed in https://github.com/watson-developer-cloud/dotnet-standard-sdk/pull/239
