### ISSUE TITLE
URL encode all query params before making requests

### ISSUE THREAD

**Issue by surendarnatarajan** [watson-developer-cloud/dotnet-standard-sdk#200]
System.AggregateException: 'One or more errors occurred. (The API query failed with status code Unauthorized: Unauthorized) (The API query failed with status code Unauthorized: Unauthorized

This is how i have create a console app 
```
class Program
    {
        static void Main(string[] args)
        {
            NaturalLanguageUnderstandingService _naturalLanguageUnderstandingService = new NaturalLanguageUnderstandingService();

            _naturalLanguageUnderstandingService.SetCredential("<####>", "<######>");

            _naturalLanguageUnderstandingService.VersionDate = "2017-02-27";

            Parameters parameters = new Parameters()
            {
                Text = "This is very good news!!",
                Features = new Features()
                {
                    Keywords = new KeywordsOptions()
                    {
                        Limit = 8,
                        Sentiment = true,
                        Emotion = true
                    }
                }
            };
            var result = _naturalLanguageUnderstandingService.Analyze(parameters);

        }
    }
}
```
 why im i not able to hit the api and i get the above error. do i need to add my credentials in the services page as well ?

**Comment by mediumTaj** [comment]
@surendarnatarajan Are you using the correct credentials? These should not be your IBM cloud credentials. Each service has it's own set of credentials. See https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/196#issuecomment-376357821

**Comment by surendarnatarajan** [comment]
@mediumTaj Thank you for your response. Yes I am using my IBM Cloud Natural Language Understanding service credentials and not the login credentials .
I am able to run my console application but not getting the result. Getting as ****IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1.Model.AnalysisResults****
![capture](https://user-images.githubusercontent.com/20180041/38268159-07fc581e-379b-11e8-9e31-035cbd9055ae.PNG)

**Comment by mediumTaj** [comment]
You are not getting the `Unauthorized` exception anymore?

You will need to serialize the result object before printing it out. 
Instead of 

```
Console.WriteLine(result);
```

Try

```
Console.WriteLine(JsonConvert.SerializeObject(result, Formatting.Indented));
```

**Comment by surendarnatarajan** [comment]
@mediumTaj  Thank you very much !! I am at least getting some response now. But I am not getting the Emotions score. 
Can you let me know how to i get the "text" emotions score.
![image](https://user-images.githubusercontent.com/20180041/38269460-34144f26-379e-11e8-9055-a27386ef6ae0.png)

**Comment by mediumTaj** [comment]
@surendarnatarajan Are you still having issues with Natural Language Understanding?

**Comment by KarthickTC** [comment]
Above sentence with the exclamatory mark does not give any result. I just removed the exclamatory mark and passed the sentence as "This is very good news." and i could get the result with emotion object.

**Comment by mediumTaj** [comment]
@KarthickTC Sorry I missed this message. This may be an issue with query params in general. I'll see if I can URLEncode all query params before making the service call.

**Comment by mediumTaj** [comment]
I tried this query with the same parameters you used and it seems to be working. Closing this for now. Please reopen if there are still issues
