### ISSUE TITLE
[Multiple Services] Use FileStream instead of Stream when sending files to preserve filename

### ISSUE THREAD

**Issue by cobalto** [watson-developer-cloud/dotnet-standard-sdk#228]
### Steps to reproduce

I'm sending files to the service as indicated on the readme.md as follows:
```cs
using (FileStream fs = File.OpenRead(<filepath>))
{
    var result = _discovery.AddDocument(<environmentId>, <collectionId>, <configurationId>, fs as Stream);
}
```

### Expected behavior

Files being sent to service with actual file name that I'll later use on my application logic when consuming the result of quering Discovery Service. 

### Actual behavior

All files are sent with the name "filename" to the service.
And now I have HUNDREDS of files called "filename" on my workspace 🤣

### Where is the problem

On "DiscoveryService.cs", the method AddDocument(...) has the follow code block

```cs
if (file != null)
{
    var fileContent = new ByteArrayContent((file as Stream).ReadAllBytes());
    System.Net.Http.Headers.MediaTypeHeaderValue contentType;
    System.Net.Http.Headers.MediaTypeHeaderValue.TryParse(fileContentType, out contentType);
    fileContent.Headers.ContentType = contentType;
    formData.Add(fileContent, "file", "filename");
 }
```

The formData must receive the actual file name instead of "filename".

```cs
formData.Add(fileContent, "file", **_actualFileName**);
```

### Suggested solution

Change the AddDocument signature to use a FileStream instead of Stream:
```cs
DocumentAccepted AddDocument(string environmentId, 
                             string collectionId, 
                             System.IO.FileStream file = null, 
                             string metadata = null, 
                             string fileContentType = null, 
                             Dictionary<string, object> customData = null);
```

Then keep sending the file as Stream, but recover the filename from the FileStream object

```cs
if (file != null)
{
    var fileContent = new ByteArrayContent((file as Stream).ReadAllBytes());
    System.Net.Http.Headers.MediaTypeHeaderValue contentType;
    System.Net.Http.Headers.MediaTypeHeaderValue.TryParse(fileContentType, out contentType);
    fileContent.Headers.ContentType = contentType;
    formData.Add(fileContent, "file", file.Name);
 }
```

### Considerations

Tried those changes locally and they work, but since my approach will change the Interface signature, I decided to create that issue instead of do a pull request.

**Comment by mediumTaj** [comment]
@cobalto I was able to add this to the generator. Unfortunately this change will affect the Discovery, Visual Recognition, Language Translator, Speech to Text, Text to Speech and Natural Language Classifier services. I'm pushing for a release tomorrow but I won't be able to add this fix until next release on June 1.

**Comment by MrIceWolf** [comment]
This is the same issue I was having while using Visual Recognition. 
I posted an issue about it but I never recieved any feedback on it.

@mediumTaj 
If this issue is resolved you can close issue #197 as well.

**Comment by cobalto** [comment]
@mediumTaj No problem, we're still doing tests on our business logic anyway, June is a pretty fair date, we will just pretend it's working until then 🤣 

Also, we can always switch to the local modified version as a workaround for a while if really necessary. 

Thanks, man! 😎 

@MrIceWolf wow, sorry to hear that, but hope with this issue your problem get solved as well 👍

**Comment by mediumTaj** [comment]
@MrIceWolf Ah, sorry that issue got lost! Yes this should fix that issue too.

**Comment by mediumTaj** [comment]
Fixed in https://github.com/watson-developer-cloud/dotnet-standard-sdk/pull/239
