### ISSUE TITLE
[dotnet-standard-sdk] Implement WebSockets

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/dotnet-standard-sdk#24]
Implement WebSockets to stream to SpeechToText and TextToSpeech.

**Comment by mediumTaj** [comment]
@atilatosta can you handle this one?

**Comment by mediumTaj** [comment]
Nevermind about estimations - we are using GitHub Projects to track task and they don't support point estimates yet.

**Comment by atilatosta** [comment]
@mediumTaj I'm checking the implementation of websockets in the dotnet standard library, but from what I'm seeing, we'll have problems. :(

**Comment by mediumTaj** [comment]
What kind of issues do you see? Is there no websocket library .NET Standard? Is there a way to get microphone access or play audio?

**Comment by atilatosta** [comment]
@mediumTaj I'm unsure about saying that WebSocket is not supported, but I'm not finding enough documentation. I believe there are third-party libraries, but I would like to use dotnet core's native libraries to the fullest. In case the SDK would not have access to the microphone or camera, who would do this would be the local application that would provide Stream to the SDK.

**Comment by mediumTaj** [comment]
Yeah I think it would be best to use .NET Core native as well. I don't have any experience in that. Unity SDK used a 3rd party plugin. I think for things that developers have a standard plugin they use, it's fine to go 3rd party. For example, for the last .NET Platform SDK I was working on I used NAudio to get access to the microphone. It might be the case where we have to leave access to the camera/microphone to the developer depending on what platform they will use unless there is a viable cross platform solution.

**Comment by mediumTaj** [comment]
@atilatosta I just talked to German. We don't need to worry about accessing the microphone, camera, etc. We just need to be able to stream a bytearray to the services. It will be the developer responsibility to connect their application to the stream

**Comment by atilatosta** [comment]
@mediumTaj Yes. That is it. We are receiving the stream, but i am still worry with websockets. I keep looking about this.

**Comment by mediumTaj** [comment]
@atilatosta Has there been any progress in WebSockets at all?

**Comment by atilatosta** [comment]
@mediumTaj Not yet, I'm doing some testing with the System.Net.Websockets namespace but still unsuccessful. In parallel I'm seeing some third party components, but the ones I saw did not work. I'm still studying this.

**Comment by mediumTaj** [comment]
OK Thanks for the update! Let me know if I can help in any way

**Comment by atilatosta** [comment]
@mediumTaj i developed an example using dotnet core and websocket. I was able to connect, send and receive data. I will create the branch of this issue and develop.

**Comment by RMichaelPickering** [comment]
Gentlemen, based on reading through this issue it appears that Websockets should be working but I haven't found any example. Could you please clarify? Is there an example of how to call Watson Speech To Text using Websocket API using C# and the IBM Watson Developer Cloud .NET SDK?
