### ISSUE TITLE
SetCredential(APiKey) is not correct

### ISSUE THREAD

**Issue by mstama** [watson-developer-cloud/dotnet-standard-sdk#247]
The translator api documentation says that the api key authentication used basic authentication: https://www.ibm.com/watson/developercloud/language-translator/api/v2/curl.html?curl#authentication

The IAM uses a bearer. Tried to used the SetCredential(ApiKey) with an error after another. Then used the SetCredential(username, password) passing "apikey", {generated api key} and the it just worked.

**Comment by mediumTaj** [comment]
`SetCredential(apikey)` is only for the VisualRecognition service. I raised an issue to move this from the base service class to the VisualRecognition service. To authenticate with an iam apikey use tokenoptions:

https://github.com/watson-developer-cloud/dotnet-standard-sdk#iam-authentication

You can also use `SetCredential(TokenOptions options)` to authenticate using iam apikey. While it's possible to authenticate using basic auth apikey:<apikey> it's not recommended.  

Closing this issue but please let me know if this doesn't help.
