### ISSUE TITLE
[speech-to-text] SpeechToTextService.Recognize call throws ServiceReponseException "The API query failed with status code Unauthorized: Processed" when using IamApiKey authentication.

### ISSUE THREAD

**Issue by acollard** [watson-developer-cloud/dotnet-standard-sdk#261]
I used the following code:
```C#
using(var fs = File.OpenRead("C:\test.wav")){
  var service = new SpeechToTextService(new TokenOptions { IamApiKey = "apikey from Speech to Text Credentials in the dashboard" });
  var response = service.Recognize("audio/wav", fs );
}
```

The Recognize call returns unauthorized status code with the reason phrase "Processed". The auth challenge header (WWWAuthenticate) in the response has the value: Basic realm="IBM Watson Gateway(Log-in)".

I know the API Key I am using is valid because I am able to return a valid token from https://iam.bluemix.net/identity/token.

All documentation seems to use username:password authentication. It would be nice if this code repository included an example for speech to text with API Key authentication.

### SDK Version
IBM.WatsonDeveloperCloud.SpeechToText.v1: 2.4.2

### Steps to reproduce
1. Create a Speech-To-Text lite plan.
2. Navigate to the dashboard: https://console.bluemix.net/dashboard/apps.
3. Retrieve API Key credentials for the Speech-To-Text service.
4. Create .Net Core console app.
5. Add IBM.WatsonDeveloperCloud.SpeechToText.v1 nuget package to the new project.
6. Add the code above to the program main method and update the IamApiKey value with the credentials found in step 3. Also update the File.OpenRead to point at a valid wav file if needed.
7. Run code, exception thrown during recognize call.

### Expected behavior
SpeechToTextService should work with IAM API Keys and the session-less recognize call should return the result.

### Actual behavior
When using IAM API Key authentication the session-less recognize call throws the exception ServiceResponseException: The API query failed with status code Unauthorized: Processed.

**Comment by acollard** [comment]
@mediumTaj Any updates on this? This is preventing us from using IBM Watson.

**Comment by mediumTaj** [comment]
@acollard let me find some time today to look at this

**Comment by mediumTaj** [comment]
What region are you using? The default service URL is US South and I don't think they've moved to RC yet. They are still using username/password. 

If you are using a service outside of US South you will need to specify the service url as well
```C#
TokenOptions tokenOptions = new TokenOptions()
{
    ServiceUrl = "https://gateway-wdc.watsonplatform.net/speech-to-text/api",  // service url for US East
    IamApiKey = "<iam-apikey>"
};

service = new SpeechToTextService(tokenOptions);
SpeechRecognitionResults response = null;
using (var fs = File.OpenRead("C:\test.wav"))
{
    response = service.Recognize("audio/wav", fs);
}

Console.WriteLine("Recognize() succeeded:\n{0}", JsonConvert.SerializeObject(response, Formatting.Indented));
```

**Comment by acollard** [comment]
@mediumTaj Your above example works. I was missing the ServiceUrl and it was defaulting to "https://iam.bluemix.net/identity/token". Thanks for the help.

I am in US East, so I used the ServiceUrl specified in my STT credentials (which is the same as yours above) and it worked.

I think initially I was confused by the IAM authentication documentation here: https://console.bluemix.net/docs/services/watson/getting-started-iam.html#iamtoken

The example they gave was:
curl -k -X POST \
  --header "Content-Type: application/x-www-form-urlencoded" \
  --header "Accept: application/json" \
  --data-urlencode "grant_type=urn:ibm:params:oauth:grant-type:apikey" \
  --data-urlencode "apikey={api_key}" \
  "https://iam.bluemix.net/identity/token"

So I assumed this was the token endpoint used for all services. Which is why it was failing when I presented this access token to the STT service endpoints. 

Not sure if this is the plan but it would be nice if the same token endpoint was used for all services, and  something like Access Token Scope (https://tools.ietf.org/html/rfc6749#page-23) was used to define what services you want the token for. There may be better verbs but that is the first one that came to mind.

**Comment by mediumTaj** [comment]
There are two urls that can be defined in the tokenOptions - `ServiceUrl` and `IamUrl`. The `ServiceUrl` should default to the US South endpoint of the service you're trying to use. The `IamUrl` should default to `https://iam.bluemix.net/identity/token`. Is the `ServiceUrl` defaulting to the `IamUrl` value? If so I'll look into that as well. 

The token endpoint should be the same for services across regions (for now). The only thing you should have to do is explicitly set the `ServiceUrl` since it's not in US South.

**Comment by acollard** [comment]
You are right, sorry while I was reviewing the TokenManager code late last night I forgot that there are 2 Url properties on the TokenOptions class and thought the value I was setting (ServiceUrl) was being used for the auth endpoint. As you point out the ServiceUrl is the endpoint for the service.

I think it would be a little more self explanatory if TokenOptions didn't have the ServiceUrl property at all since it is unrelated to the auth. Also I think not requiring a ServiceUrl in the service constructor is a bad idea, if people don't specify it then it just works for some people (US South) but then fails for everyone else using the exact same code.

Personally I think you should force the endpoint in the constructor:
```C#
public SpeechToTextService(string endpoint) : base(SERVICE_NAME, endpoint)
{
}

public SpeechToTextService(string endpoint, TokenOptions options) : this(endpoint){
}
```

**Comment by mediumTaj** [comment]
Yes this makes sense. I have something similar to this for the Unity SDK but wrapped in a Credentials object. I'll create an issue to implement something like this next major release. 

Closing this - please let me know if you have any more issues!
