### ISSUE TITLE
IClient and IRequest use Async incorrectly.

### ISSUE THREAD

**Issue by acollard** [watson-developer-cloud/dotnet-standard-sdk#263]
IClient and IRequest use of Async is not a standard way of handling Async in .Net. 

The expectation is IClient.PostAsync would return an awaitable object (like Task) that has already been initiated. In reactive extensions (http://reactivex.io/documentation/observable.html) they would call this a Hot task vs your Cold task implementation. I don't think there are any examples of Cold tasks in the .Net Framework.

### Example
.Net HttpClient
```C#
using(var client = new HttpClient()){
  var sendTask = client.GetAsync("https://www.ibm.com");
  /// Request has been sent, we are just not waiting on the response yet. This is a Hot task.
  var response = await sendTask;
}
```
IBM Watson SDK
```C#
using(var client = new WatsonHttpClient()){
  var request = client.GetAsync("https://www.ibm.com");
  /// Request has not been sent, it will only send when awaited. This is a Cold task.
  var response = await request;
}
```

### Solution
Make the IClient implementation more inline with .Net Framework.

1. Change all methods that return IRequest on IClient to not have the "Async" prefix. (ex. Get()).
2. IRequest should not have "TaskAwaiter<IResponse> GetAwaiter();".
3. Add Task<IResponse> SendAsync(IRequest request, CancellationToken cancellation = default(CancellationToken)) to IClient.
4. IRequest should not inherit from IResponse.

If you want to keep IClient.GetAsync() then it should execute immediately. See https://github.com/mono/mono/blob/master/mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs for inspiration.

The end result is:
```C#
using(var client = new WatsonHttpClient()){
  var request = client.Get("https://www.ibm.com")
    .WithHeader("Content-Type", contentType)
    .WithHeader("Content-Language", contentLanguage)
    .WithHeader("Accept-Language", acceptLanguage)
    .WithBody<ToneInput>(toneInput);
  var response = await client.SendAsync(request);
}
```

**Comment by acollard** [comment]
Instead of keeping IClient.Get/Put/Post/Delete which returns IRequest, a better option may be to add a new  method called IClient.CreateRequest(string method). This way it wouldn't confuse users when IClient.GetAsync("https://www.ibm.com") returns Task<IResponse>.

**Comment by atilatosta** [comment]
@acollard thank you! I'm thinking a little more about this.

**Comment by mediumTaj** [comment]
FYI I still really want to implement this. Looking for some time and hopefully some help

**Comment by mediumTaj** [comment]
still planning this

**Comment by mediumTaj** [comment]
Still active

**Comment by mediumTaj** [comment]
Still active
