### ISSUE TITLE
[dotnet-standard-sdk] Enforce coding standards

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/dotnet-standard-sdk#29]
Enforce coding standards on AppVeyor build. One suggestion is StyleCop.

https://github.com/StyleCop/StyleCop

Any other suggestions?

**Comment by mediumTaj** [comment]
#26

**Comment by atilatosta** [comment]
@mediumTaj seeing this page (https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md), they using the .Net Codeformatter tool to enforce coding standards, but i do not found on nuget. What do you think?

**Comment by mediumTaj** [comment]
Yeah it looks like they don't have a NuGet package

https://github.com/dotnet/codeformatter/issues/201

But this issues says 
```
The GitHub guys (@shiftkey) have rolled their own package which is perfect but it has been customized for their coding convention used in Octokit -> https://www.nuget.org/packages/Octokit.CodeFormatter/1.0.0-preview
```

We cant really use this package as a dependency though.

**Comment by mediumTaj** [comment]
Look into https://github.com/DotNetAnalyzers/StyleCopAnalyzers

**Comment by mediumTaj** [comment]
Still active
