### ISSUE TITLE
Connet to Watson Assistant with .Net c#

### ISSUE THREAD

**Issue by danieldr14** [watson-developer-cloud/dotnet-standard-sdk#290]
I have had problems trying to use the classes and connect the Watson APIs trying to use the code in GitHub:

https://github.com/watson-developer-cloud/dotnet-standard-sdk

Is there any example since the _conversation creation?

**Comment by mediumTaj** [comment]
Can you be more specific what kind of issue you are having? 

**Authenticating**
https://github.com/watson-developer-cloud/dotnet-standard-sdk#supplying-the-iam-api-key

**Assistant Service Readme**
https://github.com/watson-developer-cloud/dotnet-standard-sdk#supplying-the-iam-api-key

**Comment by parth170896** [comment]
```
NaturalLanguageUnderstandingService _naturalLanguageUnderstandingService = new NaturalLanguageUnderstandingService("2908774d-8922-45f1-86bc-c6950e50be01", "L3xDJvMUnhqR", "2018-03-16");
            Parameters parameters = new Parameters()
            {
                Text = obj.body,
                Features = new Features()
                {
                    Keywords = new KeywordsOptions()
                    { 
                        Sentiment = true,
                        Emotion = true
                    }
                }
            };

            AnalysisResults result = _naturalLanguageUnderstandingService.Analyze(parameters);
            SentimentResult r2 = result.Sentiment;
            if (r2 != null)
            {
                Console.WriteLine("Point 1");
            }
            else
            {
                Console.WriteLine("Point 2");
            }

```
I have written above code for using watson nlu sdk. But its showing null pointer exception every time i try to access sentiment and emotions. So help me to access this...

**Comment by mediumTaj** [comment]
Closing this as there has been no response since September
