### ISSUE TITLE
[text-to-speech] MissingMethodException System.Net.Http

### ISSUE THREAD

**Issue by aryus96** [watson-developer-cloud/dotnet-standard-sdk#307]
Hello,

I'm currently trying to develop a simple program with the followings tools & libs :
- Visual Studio Community, W10 x64
- .NET 4.6.1
- IBM.WatsonDeveloperCloud 2.11.0 (Installed through NuGet)
- IBM.WatsonDeveloperCloud.TextToSpeech.v1 2.11.0 (Installed through NuGet)

However, I can't run the following code : 

>TextToSpeechService _TtS = new TextToSpeechService(T1);  
> t1 = new Text { _Text = "Hello World" }; 
>var m1 = _TtS.Synthesize(t1); 

The error occur at the method Synthesize(t1).

>System.MissingMethodException : 'Méthode introuvable : System.Collections.ObjectModel.Collection`1<System.Net.Http.Headers.MediaTypeHeaderValue>  System.Net.Http.Formatting.MediaTypeFormatter.get_SupportedMediaTypes()'.'

Tried to solve by :
- Downgrading System.Net.http from 4.3.4 to 4.0.0 
- Installing System.Net.Http.Formatting.Extension 5.2.3
- Installing Wdc.System.Net.Http.Formatting.NetStandard 1.0.7 
- Updating all the libs through NuGet

Thank you,

**Comment by ppedro74** [comment]
Hi,
I had the same issue when using the SDK with Windows .NET 4.6.1, although it works well with .NET CORE Console application.

I replicate your problem and i fixed the project to work check my repo: 
https://github.com/ppedro74/IBMWatson-playground

**Comment by aryus96** [comment]
Hi @ppedro74 ,

Thank you for your help. However I couldn't run your program.
Opening an issue on your repository about your solution.

Cheers,

**Comment by aryus96** [comment]
It's finally working. A big thanks to @ppedro74 and to @dluxfordhpf .
Here are the steps if you encounter the same problems :

- Install all your required IBM.Watson plugins with NuGet.
- Go to NuGet again, search for System.Net.Http
- In the right hand pane, scroll down a little bit and set the Dependency behaviour to Ignore Dependencies.
- Right above, you can check the Preview Window to be sure that only this package is being modified.
- Open the CSPROJ file for this project in a text editor.
- In /Project/PropertyGroup*1 (the first PropertyGroup element of Project), add the following line, or change the value of this element if it already exists:

`<AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>`
- Save the file, then reload the project in Visual Studio.
- Open the app.config file for this project.
- Find the line for System.Net.Http and edit it to redirect it to 4.0.0.0 instead of 4.1.0.0. So find this:

`<dependentAssembly> 
<assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" /> 
<bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" /> 
</dependentAssembly> `

And change it to this : 

`<dependentAssembly> 
<assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" /> 
<bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.0.0.0" /> 
</dependentAssembly> `

- Rebuild the project.

I personally still have the following warning, but it's running :

> warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information,
