### ISSUE TITLE
Issue with Content-Language and headers in ToneAnalyzer?

### ISSUE THREAD

**Issue by BouchardClaude** [watson-developer-cloud/dotnet-standard-sdk#309]
ContentLanguage does not look like its working. From what I understand, the accept-language header is working, but not Content-Language, preventing me of  using the sdk with french text.  Not sure I understand how the headers are set, but i'm not sure the TryAddWithoutValidation of Reqests.cs are working properly. 

When you instanciante a ToneAnalyzerSErvice: 
               ` if (!string.IsNullOrEmpty(contentLanguage))

                    restRequest.WithHeader("Content-Language", contentLanguage);
                if (!string.IsNullOrEmpty(acceptLanguage))
                    restRequest.WithHeader("Accept-Language", acceptLanguage);
                if (sentences != null)`

this is the code called
        `public IRequest WithHeader(string key, string value)`

        {
            if (key == "Accept" && value.StartsWith("audio/", StringComparison.OrdinalIgnoreCase))
            {
                this.Message.Headers.Accept.Clear();
            }
            this.Message.Headers.TryAddWithoutValidation(key, value);
            return this;
        }

Project in .net Framework 4.6.1

**Comment by mediumTaj** [comment]
Can you tell me if this is still happening and can you provide code to reproduce?

**Comment by BouchardClaude** [comment]
unfortunalty as I got no answer I gave up and dont have the code anymore. I guess you can close the issue as I dont have time to look at it for the next weeks.
 thx anyway.
