### ISSUE TITLE
[PersonalityInsights] Unable to install packages into dotnet core 2.2.100 app

### ISSUE THREAD

**Issue by idvorkin** [watson-developer-cloud/dotnet-standard-sdk#316]
## Steps to reproduce
- Create new dotnet application
- Add package via: 
      dotnet add package IBM.WatsonDeveloperCloud.PersonalityInsights.v3 --version 2.12.0
## Expected behavior
     Able to add reference
## Actual behavior

```
idvor@IGORBASEMENTHP C:\gits\google-nlp
> dotnet add package IBM.WatsonDeveloperCloud.PersonalityInsights.v3 --version 2.12.0
  Writing C:\Users\idvor\AppData\Local\Temp\tmp3042.tmp
info : Adding PackageReference for package 'IBM.WatsonDeveloperCloud.PersonalityInsights.v3' into project 'C:\gits\google-nlp\google-nlp.csproj'.
log  : Restoring packages for C:\gits\google-nlp\google-nlp.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/ibm.watsondevelopercloud/index.json
error: Unable to find package IBM.WatsonDeveloperCloud with version (>= 2.12.0)
error:   - Found 24 version(s) in nuget.org [ Nearest version: 2.11.0 ]
error:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
error: Package 'IBM.WatsonDeveloperCloud.PersonalityInsights.v3' is incompatible with 'all' frameworks in project 'C:\gits\google-nlp\google-nlp.csproj'.
```     

## .NET SDK version
```
> dotnet --version
2.2.100
```

**Comment by germanattanasio** [comment]
Thanks a lot for filing this issue! We'll triage and take a look at it as soon as possible!

**Comment by idvorkin** [comment]
Touching now that the holidays are over!

**Comment by mediumTaj** [comment]
Thanks for the reminder @idvorkin - looking into this. One thing I noticed was the package for `IBM.WatsonDeveloperCloud` v2.12.0 failed to publish to nuget. looking into it.

**Comment by mediumTaj** [comment]
I published `IBM.WatsonDeveloperCloud` v2.12.0 to NuGet. I don't think that's the issue though. The Watson SDK is build using .NET Standard 1.3 so only .NET Core 1.0 is supported

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

We are looking into moving to .NET Standard 2.0 in the next major release!

**Comment by mediumTaj** [comment]
Closing this but please let me know if you have any more questions about this.
