### ISSUE TITLE
User-Agent HTTP header string with invalid format

### ISSUE THREAD

**Issue by diegoortizmatajira** [watson-developer-cloud/dotnet-standard-sdk#342]
**Overview**
When consuming API objects (i.e. `IBM.WatsonDeveloperCloud.Assistant.v2` v.2.16.0) we are getting an exception when running from linux:

```
System.FormatException: The format of value '4.19.28-1-MANJARO#1SMPPREEMPTSunMar1008:32:42UTC2019 .NETCore4.6.27306.03' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at IBM.WatsonDeveloperCloud.Http.HttpFactory.GetRequestMessage(HttpMethod method, Uri resource, MediaTypeFormatterCollection formatters)
   at IBM.WatsonDeveloperCloud.Http.WatsonHttpClient.SendAsync(HttpMethod method, String resource)
   at IBM.WatsonDeveloperCloud.Util.TokenManager.RequestToken()
   at IBM.WatsonDeveloperCloud.Util.TokenManager.GetToken()
   at IBM.WatsonDeveloperCloud.Assistant.v2.AssistantService.CreateSession(String assistantId, Dictionary`2 customData)
```

**Expected behavior**
It should build the Http Client with a valid User-Agent string value and consume the API correctly

**Actual behavior**
The User-Agent value (Built on `IBM.WatsonDeveloperCloud.Http.HttpFactory` class and `GetRequestMessage` method) is returning a value '4.19.28-1-MANJARO#1SMPPREEMPTSunMar1008:32:42UTC2019 .NETCore4.6.27306.03' that is not valid throwing an exception

**How to reproduce**
Consume the API objects (i.e. `IBM.WatsonDeveloperCloud.Assistant.v2`) from Linux (I've used Manjaro and Ubuntu on Azure DevOps)

**Screenshots**
Not applicable

**SDK Version**
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.102
 Commit:    96ff75a873

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.2.102/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.102 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.1 [/opt/dotnet/shared/Microsoft.NETCore.App]

```
**Additional information:**
- OS: Manjaro Linux x86_64 
- Kernel: 4.19.28-1-MANJARO 
- Which version of `Dotnet` are you using? dotnet 2.2.102

**Additional context**
Source of problem identified on method `GetRequestMessage` of [`IBM.WatsonDeveloperCloud.Http.HttpFactory`](https://github.com/watson-developer-cloud/dotnet-standard-sdk/blob/master/src/IBM.WatsonDeveloperCloud/Http/HttpFactory.cs) class in the watson-developer-cloud SDK

Related to code merged on #329 
Related to #335

**Comment by mediumTaj** [comment]
Can you give me what you get for 
```
System.Runtime.InteropServices.RuntimeInformation.OSDescription;
```

**Comment by diegoortizmatajira** [comment]
It returns: "`Linux 4.19.28-1-MANJARO #1 SMP PREEMPT Sun Mar 10 08:32:42 UTC 2019`"

**Comment by mediumTaj** [comment]
Can you see if this PR fixes the user-agent parsing issue?
https://github.com/watson-developer-cloud/dotnet-standard-sdk/pull/344
