### ISSUE TITLE
[translator] Default constructor is missing a parameter

### ISSUE THREAD

**Issue by mstama** [watson-developer-cloud/dotnet-standard-sdk#350]
The default constructor implementation is missing a parameter to be passed to the base class.

The default constructor have the following implementation:
```cs
public LanguageTranslatorService() : base(SERVICE_NAME) { }
```
while all the other implementation passes the URL constant to the base class:
```cs
public LanguageTranslatorService(string userName, string password, string versionDate) : base(SERVICE_NAME, URL)
```

```cs
public LanguageTranslatorService(TokenOptions options, string versionDate) : base(SERVICE_NAME, URL)
```

```cs
public LanguageTranslatorService(IClient httpClient) : base(SERVICE_NAME, URL)
```

That leads to the endpoint in the base class to have an empty string and generates an error when calling the translate method.

**Comment by mediumTaj** [comment]
Hi @mstama, The default constructor is used when authenticating using a credentials file. 

```
https://github.com/watson-developer-cloud/dotnet-standard-sdk#credential-file-easier
```

Use the other constructors to authenticate either using IAM or BasicAuth.
