### ISSUE TITLE
face recognition in unity 3d 

### ISSUE THREAD

**Issue by Arvind2468** [watson-developer-cloud/dotnet-standard-sdk#351]
[face recognition]- can i recognize face by using unity3d software for mobile application through camera?

**Comment by mediumTaj** [comment]
Please use the Unity SDK

https://github.com/watson-developer-cloud/unity-sdk

To get the webcam data you will need to use [WebCamTexture](https://docs.unity3d.com/ScriptReference/WebCamTexture.html).

**Comment by Arvind2468** [comment]
Respected sir,
Can you tell the procedure how to do it?
Thank you

**Comment by Arvind2468** [comment]
how can i do it ? how can i train my classifier through code? can you please elaborate?
