### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by smoralesingsoft** [watson-developer-cloud/dotnet-standard-sdk#386]
The README Links are Brokens

![2019-07-26_182146](https://user-images.githubusercontent.com/47360129/61984278-bb7bf700-afd1-11e9-9c56-cba2b0b761ec.png)
![2019-07-26_182205](https://user-images.githubusercontent.com/47360129/61984285-bf0f7e00-afd1-11e9-8a58-77ea876d8647.png)

**Comment by mediumTaj** [comment]
Thanks for the issue - I will take a look at generating this.
