### ISSUE TITLE
[dotnet-standard-sdk] Support Multipart Form Data

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/dotnet-standard-sdk#40]
Many services depend on data being sent as Multipart Form data. We need to be able to add data to the http request as Form data and not just body.

For `LanguageTranslation` to call the method `CreateModel` we need to send a file as form data with the names of (one or more) `forced_glossary`, `paralell_corpus` and/or `monolingual_corpus`.

https://watson-api-explorer.mybluemix.net/apis/language-translator-v2#!/models/customTranslationModels

http://www.ibm.com/watson/developercloud/language-translator/api/v2/?node#create-model

Currently we are sending this as body data. We need to be able to send the file as a bytearray in form data.

From `LanguageTranslatorService.cs`
```
                StreamContent content = new StreamContent(file);
                content.Headers.Add("Content-Type", "text/xml");

                result =
                    this.Client.WithAuthentication(this.UserName, this.Password)
                                .PostAsync($"{this.Endpoint}{PATH_MODEL}")
                                .WithArgument("base_model_id", baseModelId)
                                .WithArgument("name", name)
                                .WithBodyContent(content)
                                .As<CustomModels>()
                                .Result;
```

See the [Unity SDK](https://github.com/watson-developer-cloud/unity-sdk/blob/develop/Scripts/Connection/RESTConnector.cs#L378-L404) for how Forms were implemented.

**Comment by atilatosta** [comment]
@mediumTaj i fix this issue but when i call the CreateModel endpoint on Language Translator service, both for watson explorer and a service in my bluemix account, i got  this error:

supplied bluemix-plan-id does not permit access to customization

Have any idea?

**Comment by mediumTaj** [comment]
@atilatosta Awesome! that would be because the free plan cannot make custom models. Let me see if I can get credentials

**Comment by mediumTaj** [comment]
@atilatosta So can any service send form data now? If so I can continue abstracting services.

**Comment by mediumTaj** [comment]
Hmm @atilatosta I sent credentials to your ibm email

**Comment by atilatosta** [comment]
@mediumTaj No! It's necessary fix each operation of the abstractions. i will check the others abstractions.

**Comment by mediumTaj** [comment]
@atilatosta Is there any way to implement this similar to how [RESTSharp](https://github.com/restsharp/RestSharp/wiki/Recommended-Usage) works? 

>All of the values added via AddParameter in this example will be submitted as a standard encoded form, similar to a form submission made via a web page. If this were a GET-style request (GET/DELETE/OPTIONS/HEAD), the parameter values would be submitted via the QueryString instead. You can also add header and cookie parameters with AddParameter(). To add all properties for an object as parameters, use AddObject(). To add a file for upload, use AddFile() (request will be sent as multipart encoded form). To include a request body (like XML or JSON), use AddBody();

**Comment by mediumTaj** [comment]
@atilatosta did you see this com,ent? ^
