### ISSUE TITLE
Speech To Text with Live Mic Input

### ISSUE THREAD

**Issue by nathannzw** [watson-developer-cloud/dotnet-standard-sdk#418]
Will there be sample code available for this feature in C#? nodejs has this.

**Comment by mediumTaj** [comment]
We hope to add this eventually. It may be a while because of low bandwith.

**Comment by mediumTaj** [comment]
That being said, we are open to reviewing pull requests if you have time to add support!

**Comment by nathannzw** [comment]
Ok, thank you. Will look out for this!

**Comment by mediumTaj** [comment]
Closing this as we have an internal issue open
