### ISSUE TITLE
SpeechToTextService does not support IamAuthenticator as a constructor as per the examples on this site.

### ISSUE THREAD

**Issue by HayS33d** [watson-developer-cloud/dotnet-standard-sdk#427]
The examples on  this site are outdated per the new SpeechToTextService constructor overloads. 
IamAuthenticator is no longer used with version 2.17

**Comment by mediumTaj** [comment]
Please use the updated package `IBM.Watson.SpeechToText.v1`. The .NET SDK moved to the new namespace a few major versions ago and the WatsonDeveloperCloud namespace has been deprecated.
