### ISSUE TITLE
What about C++ ?

### ISSUE THREAD

**Issue by POWER-KI** [watson-developer-cloud/dotnet-standard-sdk#428]
I would like to know if you have plan for a C/C++ (WIN) implementation of the SDK.
I would like to write a wrap for a programming language so I need a fast execution (No: python, java, javascript, c# ..).

Thank you. 
CAP
p.s. I am not sure to be in the right place to pose the question but ..

**Comment by germanattanasio** [comment]
Hi @POWER-KI what are your requirements that you need to write a C++ SDK? what do you mean by fast execution? Remember that you have to always wait for Watson to reply and that will always be greater than whatever code your run.

**Comment by getcontext** [comment]
Hi,

It would be great to port c# or java part into c++.
As I am in IBM , I was thinking of doing so, but I'm in a different
project.
There is a bit of work on it, but it's doable.

cheers,a


pon., 15 cze 2020 o 19:32 German Attanasio <notifications@github.com>
napisał(a):

**Comment by POWER-KI** [comment]
As you can argue from this link [www.POWER-KI.com ](url) we would like  to make a WRAP DLL for the POWER-KI programming language. The better and fast way (all is ready for this) is to start from C o C++. 
Thank you,
CAP

**Comment by mediumTaj** [comment]
Not an issue with the .NET SDK, closing. We will take the comment into consideration.
