### ISSUE TITLE
How to use IBM Watson Speech-To-Text API

### ISSUE THREAD

**Issue by FurkanGozukara** [watson-developer-cloud/dotnet-standard-sdk#439]
I have registered and downloaded my API key

I have composed a .NET core console application and installed IBM.Watson.SpeechToText.v1 via NuGet package

So I am ready but I cant find any documentation for how to read an MP3 audio file and convert it to the text

![image](https://user-images.githubusercontent.com/19240467/95303167-8a60ad00-088b-11eb-88e8-b40073e4e637.png)

**Comment by kevinkowa** [comment]
Hi @FurkanGozukara! Please take a look at [https://cloud.ibm.com/apidocs/speech-to-text?code=dotnet-standard#recognize](https://cloud.ibm.com/apidocs/speech-to-text?code=dotnet-standard#recognize), and let me know if that helps you out
