### ISSUE TITLE
StartObject error in v5 calling ListDialogNodes

### ISSUE THREAD

**Issue by kdubious** [watson-developer-cloud/dotnet-standard-sdk#447]
-- Edited to include a more proper bug report

**Overview**
Calling `ListDialogNodes` against an asstant with a node containing a Transfer to human Agent fails with the error:
`Error reading string. Unexpected token: StartObject. Path 'agent_available', line 1, position 9303.`

**Expected behavior**
Expect to get a result set

**Actual behavior**
`Error reading string. Unexpected token: StartObject. Path 'agent_available', line 1, position 9303.`

**How to reproduce**
1. Add a node, include a response with "Connect to human agent" response type.
2. Use the .NET SDK to call `ListDialogNodes`

**Screenshots**

**SDK Version**
v5

**Additional information:**
- OS: Windows
- Which version of `Dotnet` are you using? Core 5

**Additional context**
Removing the response type resolves the error

**Comment by kevinkowa** [comment]
Hi @kdubious, can you fill out the bug report so we can tackle this problem?

**Comment by kdubious** [comment]
@kevinkowa I almost didn't submit this one for exactly that reason. ;)

I upgraded a project to the newest 5.0 Nuget packages. I called:
` var rslt = assistant.ListDialogNodes(workspaceId, includeAudit: true).Result`
and I got the error I mentioned in the title. I reverted to the previous (4.6) package and all is well.

I don't have time right now to go back to 5.0 and get you any more details.

**Comment by kevinkowa** [comment]
@kdubious No problem! I haven't been able to reproduce this error. Is there anything in particular that you remember doing? A larger snippet of code might help too

**Comment by kdubious** [comment]
OK, I upgraded again to v5. Same issue:

Error reading string. Unexpected token: StartObject. Path 'agent_available', line 1, position 9303.

![image](https://user-images.githubusercontent.com/9756166/102529324-b6f42a80-406d-11eb-974f-96141d176029.png)

**Comment by kdubious** [comment]
One of my nodes has a Transfer To Agent:

        {
          "output": {
            "generic": [
              {
                "values": [
                  {
                    "text": "Hang tight..."
                  }
                ],
                "response_type": "text",
                "selection_policy": "sequential"
              },
              {
                "title": "Title here",
                "source": "https://th.bing.com/th/id/OIP.WG93se6OrBKzkps0Ns3JAAHaOn?pid=Api&rs=1",
                "description": "descr here",
                "response_type": "image"
              },
              {
                "response_type": "connect_to_agent",
                "transfer_info": {
                  "target": {}
                },
                "agent_available": {
                  "message": ""
                },
                "agent_unavailable": {
                  "message": ""
                },
                "message_to_human_agent": "Transfer coming your way"
              }
            ]
          }
        }

**Comment by kdubious** [comment]
And... if I remove that Response, it works.

**Comment by kevinkowa** [comment]
@kdubious Thank you for the information, we will fix it as soon as possible!

**Comment by kevinkowa** [comment]
Hi @kdubious feel free to try out the latest version: 5.0.1 with the fix for this issue

**Comment by kdubious** [comment]
@kevinkowa Excellent, thanks. I've been using the NuGet packages (not source code), but I may download it just for this fix.

**Comment by mediumTaj** [comment]
Kevin, can you check to see if the updated packages were deployed to nuget?

**Comment by kdubious** [comment]
@mediumTaj I don't see them: https://www.nuget.org/packages/IBM.Watson.Assistant.v2

![image](https://user-images.githubusercontent.com/9756166/102896912-29ca2080-4435-11eb-88b1-05053a906894.png)

**Comment by kevinkowa** [comment]
It's up in nuget now, https://www.nuget.org/packages/IBM.Watson.Assistant.v2/5.0.1.
Let me know if there's anything else I can help with!

**Comment by kdubious** [comment]
@kevinkowa & @mediumTaj, I got the latest from NuGet... problem solved. Thanks!

(Only thing I need now is a few clients looking to have Watson Assistant chatbots built.)
