### ISSUE TITLE
Support for web request proxy

### ISSUE THREAD

**Issue by darkmatter2222** [watson-developer-cloud/dotnet-standard-sdk#452]
Super Simple,

We are using this SDK behind a corporate proxy. This SDK does not enable the developer to set the proxy prior to the web request is made to IBM Cloud. Prime example: https://github.com/watson-developer-cloud/dotnet-standard-sdk/blob/1af67675044bda3b1647ba4e4bea9f5104fce923/src/IBM.Watson.Discovery.v2/DiscoveryService.cs#L103

Solutions like the one outlined [here ](https://stackoverflow.com/questions/58622667/connect-to-watson-discoveryservice-through-a-proxy-using-net-c)are extremely primitive: 

Please allow a proxy to be set at the class level to be used on each request to IBM cloud. 

I would suggest this feature be implemented for all classes [here](https://github.com/watson-developer-cloud/dotnet-standard-sdk/tree/1af67675044bda3b1647ba4e4bea9f5104fce923/src).  We came across this as part of IBM.Watson.Discovery.v2

How to set a proxy: https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest.proxy?view=net-5.0

**Comment by kevinkowa** [comment]
I'll look into this soon, thank you for bringing up this issue!

**Comment by darkmatter2222** [comment]
@kevinkowa, are you accepting contributions?

**Comment by mediumTaj** [comment]
Yes please feel free to submit a PR!

**Comment by darkmatter2222** [comment]
@mediumTaj, @kevinkowa, the right place to make this adjustment would be in the constructor of the client by feeding in proxy as a HttpClientHandler. This appears to be done in IBM.Cloud.SDK.Core.Service. Can you point me into the direction of that source. Having trouble finding it.

Outlined [here](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.proxy?view=net-5.0)

**Comment by mediumTaj** [comment]
https://github.com/IBM/dotnet-sdk-core

**Comment by kevinkowa** [comment]
@darkmatter2222 Thank you for contributing!
