### ISSUE TITLE
SSML Tags throwing error when synthesizing audio with web sockets.

### ISSUE THREAD

**Issue by GoncaloBastos** [watson-developer-cloud/dotnet-standard-sdk#460]
**Overview**
_When sending a text to be synthesized through the Text to Speech Service, an exception is thrown if SSML tags are added._

**Expected behavior**
_SSML tags are accepted and affect the result of the request_

**Actual behavior**
_An exception is raised: ` System.AggregateException: One or more errors occurred. (The remote party closed the WebSocket connection without completing the close handshake.)`_

**How to reproduce**
_Sending the following text: `<speak version="1.0"><prosody rate = "default">Hello, I am your doctor's assistant, and I am here to answer any questions you might have about your condition! Testing watsons text to speech.</prosody></speak>` will return an exception when calling `SynthesizeUsingWebSocket`_ 

**SDK Version**
_TTS.v1 5.2.0-rc1_

**Comment by mediumTaj** [comment]
Hi Goncalo, which voice are you using?

**Comment by mediumTaj** [comment]
SSML is not available in neural voices
https://cloud.ibm.com/docs/text-to-speech?topic=text-to-speech-voices

these docs list other limitations of SSML, i.e. <express-as> only being available in en-US_AllisonVoice

**Comment by jeffpk62** [comment]
@mediumTaj I believe the limitations you mention are that specific SSML features are no longer available. SSML in general is supported across all of the voices.

**Comment by GoncaloBastos** [comment]
Sorry for the late reply. We tested with a couple of neural voices. We were just trying to replicate the results from this page:

https://www.ibm.com/demos/live/tts-demo/self-service/home

which lets you adjust pitch, rate, etc. of all neural voices as far as I can tell.

**Comment by mediumTaj** [comment]
@jeffpk62 ah gotcha, I read migration wrong as ALL ssml features are not available in neural voices. @kevinkowa can you take a look

**Comment by kevinkowa** [comment]
Alright, I'll test it out

**Comment by kevinkowa** [comment]
Hi @GoncaloBastos,

My apologies for the delay. I found the solution, believe or not, it works if you do the following 
```
string testText = "<prosody rate='slow'>Hello, I am your doctor's assistant, and I am here to answer any questions you might have about your condition! Testing watsons text to speech.</prosody>";
```

**Comment by GoncaloBastos** [comment]
Interesting, I think I read somewhere that the string needs to be escaped, so that might explain why it works with the single quotes?

**Comment by jeffpk62** [comment]
Yes, you need to escape XML control chars that are part of the text that is to be synthesized.  There's some stilted information about this here:

https://cloud.ibm.com/docs/text-to-speech?topic=text-to-speech-usingHTTP#escape

There are also a bunch of possible validation errors listed here:

https://cloud.ibm.com/docs/text-to-speech?topic=text-to-speech-ssml#errors

**Comment by kevinkowa** [comment]
@GoncaloBastos you can also escape it like this
```
string testText = "<prosody rate=\\\"slow\\\">hello world</prosody>";
```
