### ISSUE TITLE
[build] Deployment Automation

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/dotnet-standard-sdk#47]
Deploy packages to NuGet when pushing to `release` branch. All checks should pass in the `development` branch before pushing to `release`.

A few things need to happen if possible
- [ ] Update `User-Agent` to the latest version
- [ ] Update each package ReadMe installation instructions
- [ ] Update each package ReadMe dependency

Alternatively, we can remove installation instructions and dependency and replace with the NuGet badge seen in the [Language Translation ReadMe](https://github.com/atilatosta/dotnet-standard-sdk/tree/development/src/IBM.WatsonDeveloperCloud.LanguageTranslator) 

@atilatosta @maykonsIBM 

I just want to start a conversation here about NuGet Deployment. 

I think we should deploy through Appveyor. I can either deploy through their automatic deployment system or write a script to generate/edit nuspec files for each package and push to NuGet. 

Should we push all packages every time a new SDK is released even if there were no changes? This would definitely be easier for automation. 

Is there a standard deployment strategy for .NET developers?

We also need the package name [IBM.WatsonDeveloperCloud](http://www.nuget.org/packages/IBM.WatsonDeveloperCloud/0.1.0-alpha) to be transferred to WDC. Is there a way to transfer it to my NuGet account for now?

**Comment by mediumTaj** [comment]
Looks like [here](http://blog.nuget.org/20130205/managing-package-owners.html) it says

>Transfering Package Ownership
We sometimes get support requests to transfer package ownership from one user to another, but you can almost always accomplish this yourself. Transfering ownership from one user to another is simply a combination of the two features above.

1. The current owner invites the new user to become a co-owner and the new user accepts the invite;
1. The new user removes the old user from the list of owners.

**Comment by mediumTaj** [comment]
@atilatosta Here are instructions for adding owners to the IBM.WatsonDeveloperCloud package:

>Once a package has been published to nuget.org, it’s easy to invite additional users to become owners of the package.
>Log on to nuget.org with the account that is the current owner of the package;
Navigate to the package page using the ‘Packages’ tab, searching, or clicking your username to and then ‘Manage My Packages’;
When logged on as the package’s owner, there is a ‘Manage Owners’ link on the left side to click;
Enter the username of the person to add as an owner and click ‘Add’;
An email is then sent to the new co-owner, as an invitation to become an owner of the package;
Once that user clicks the link, they are a full co-owner with full control over the package, including the ability to remove other users as owners.

**Comment by atilatosta** [comment]
@mediumTaj i sended to you, if you want can be remove my id. About deployment, there is no standard deployment strategy for .NET developers. I think that, if possible, only push the package if there is change.

I have one doubt, in the dotnet core it is possible to generate a package with only a "pack" command.

Example: dotnet pack --no-build --configuration release.

And this command can be executed in the "postcompile", including this configuration in the project.json of each project.
`
"Scripts": {
     "Postcompile": [
       "Dotnet pack --no-build --configuration release"
     ]
   }
`

So, do we need Nuspec?

**Comment by mediumTaj** [comment]
@atilatosta Ah, we can generate without a nuspec file? So we don't need to designate version, description , and other info that we had to populate in the nuspec?

**Comment by atilatosta** [comment]
@mediumTaj Yeah! We can generate without nuspec file, but the information of version, description and others, are in the project.json file. Look [Project.json-file](https://github.com/aspnet/Home/wiki/Project.json-file)

**Comment by mediumTaj** [comment]
Nice ok, I'll remove nuspec then. Thanks!!
