### ISSUE TITLE
Summarization Result class missing in .NET NaturalLanguageUnderstanding.v1.Model

### ISSUE THREAD

**Issue by mitestojanov1990** [watson-developer-cloud/dotnet-standard-sdk#484]
**Overview**
Inside package IBM.Watson.NaturalLanguageUnderstanding.v1.Model for class AnalysisResults there is no SummarizationResult property.
The class SummarizationResult is not present at all..

**Expected behavior**
When retrieving the results from NaturalLanguageUnderstandingService, using SummarizationOptions as a Feature I expect to get a summarization property (object with text summary) in the AnalysisResults object.

**Actual behavior**
When retrieving the results from NaturalLanguageUnderstandingService, using SummarizationOptions as a Feature there is no summarization object in the returned AnalysisResults object.

**How to reproduce**
`using IBM.Cloud.SDK.Core.Authentication.Iam;
using IBM.Watson.NaturalLanguageUnderstanding.v1;
using IBM.Watson.NaturalLanguageUnderstanding.v1.Model;

IamAuthenticator authenticator = new IamAuthenticator(apikey: API_KEY);
NaturalLanguageUnderstandingService naturalLanguageUnderstanding = new NaturalLanguageUnderstandingService("2021-08-01", authenticator);
naturalLanguageUnderstanding.SetServiceUrl(SERVICE_URL);

var entitiesOptions = new EntitiesOptions() { Emotion = true, Sentiment = true, Limit = 5 };
var keywordsOptions = new KeywordsOptions() { Emotion = true, Sentiment = true, Limit = 5 };
var summarizationOptions = new SummarizationOptions() { Limit = numberOfSentences };
var categoriesOptions = new CategoriesOptions() { Limit = 3 };
var conceptOptions = new ConceptsOptions() { Limit = 5 };
var features = new Features()
{
    Entities = entitiesOptions,
    Keywords = keywordsOptions,
    Summarization = summarizationOptions,
    Categories = categoriesOptions,
    Emotion = new EmotionOptions(),
    Sentiment = new SentimentOptions(),
    Concepts = conceptOptions
};
var result = naturalLanguageUnderstanding.Analyze(
    returnAnalyzedText: true,
    url: url,
    features: features,
    clean: true,
    language: "en"
).Result;
// result.Summarization doesn't exist.`

**SDK Version**
IBM.Watson.NaturalLanguageUnderstanding.v1 - v5.3.0

**Additional information:**
- OS: Windows 10 64bit
- .NET 4,6.1, .NET 4.7.

**Screenshots**
![analysis](https://user-images.githubusercontent.com/3868723/143613655-900b81c6-3731-4aa4-9d4f-b17a273e406d.PNG)

**Comment by kevinkowa** [comment]
This is experimental, it's not in the SDKs as of the moment.
