### ISSUE TITLE
[dotnet-standard-sdk] Microsoft.AspNet.WebApi.Client 5.2.3 is not compatible with netstandard1.6

### ISSUE THREAD

**Issue by claytonbnu** [watson-developer-cloud/dotnet-standard-sdk#73]
When creating a new project(vst 15 or 17) and getting the sdk in the nuget the following error occurs:

Restoring packages for d:\clayton\documents\visual studio 2017\Projects\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj...
Package Microsoft.AspNet.WebApi.Client 5.2.3 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.AspNet.WebApi.Client 5.2.3 supports:
  - net45 (.NETFramework,Version=v4.5)
  - portable-net45+netcore45+wp8+wp81+wpa81 (.NETPortable,Version=v0.0,Profile=wp8+netcore45+net45+wp81+wpa81)
One or more packages are incompatible with .NETStandard,Version=v1.6.
Package restore failed. Rolling back package changes for 'ClassLibrary1'.
Time Elapsed: 00:00:00.2415071
========== Finished ==========

**Comment by mediumTaj** [comment]
@atilatosta I have been adding `portable-net451+win8` to the .net core imports. Is the `WebApi.Client 5.2.3` dependency important?

```
"frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dnxcore50", "portable-net451+win8" ]
    }
  }
```

**Comment by atilatosta** [comment]
@mediumTaj Yes, because the MediaTypeFormatter (HttpFactory.cs) depends on this namespace.

@claytonbnu You are creating a .net framework project, try to create a .net core project.

**Comment by claytonbnu** [comment]
@atilatosta Same problem.

 Package Microsoft.AspNet.WebApi.Client 5.2.3 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.AspNet.WebApi.Client 5.2.3 supports:
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+netcore45+wp8+wp81+wpa81 (.NETPortable,Version=v0.0,Profile=wp8+netcore45+net45+wp81+wpa81)
    One or more packages are incompatible with .NETCoreApp,Version=v1.1.

![image](https://cloud.githubusercontent.com/assets/13488218/22900369/454e1490-f215-11e6-9ed4-7050ed85e523.png)

See this issue on aspnet.
[https://github.com/aspnet/Home/issues/1558](url)

**Comment by degrim** [comment]
@claytonbnu Your frameworks section says `netcoreapp1.1` but your dependencies section shows `Microsoft.NETCore.App` version `1.0.1`.  This is invalid.  Specifying `netcoreapp1.1` in the frameworks section will only affect building and restoring the project for .NET Core 1.1, which you currently aren't doing because of the `Microsoft.NETCore.App` dependency on version `1.0.1`.  Once that is fixed, you'll need to add `"portable-net45+netcore45+wp8+wp81+wpa81"` to your imports section.

**Comment by atilatosta** [comment]
@claytonbnu I created a console app with project.json below and it worked correctly:
```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.1"
    },
    "IBM.WatsonDeveloperCloud": "0.1.1-alpha"
  },
  "frameworks": {
    "netcoreapp1.1": {
      "imports": [ "dnxcore50", "portable-net451+win8" ]
    }
  }
}
```
Please tell me if your Visual Studio is with Update 3 and you have at least DotNetCore.1.0.1-VS2015Tools.Preview2.0.3 installed as well.

However, the package "IBM.WatsonDeveloperCloud" is just the core of the libraries. If you want to use the services, you should use the specific package of each, eg IBM.WatsonDeveloperCloud.LanguageTranslator ...

**Comment by claytonbnu** [comment]
It worked in another pc!
My Visual Studio was all up to date, with sp3 and and lastest tools.
I open the project on another pc with visual studio and it worked. :/

thank you so much for the support.

**Comment by atilatosta** [comment]
@claytonbnu great news! You're welcome!
