### ISSUE TITLE
[dotnet-standard-sdk] SDK Service Versioning

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/dotnet-standard-sdk#76]
## _As a_ developer, _I want_ service versioning, _so that_ I can consume services by version.

**Context:**

Currently the .NET SDK services are loosely versioned. Each service has a package with a single readme, set of integration and unit tests and example projects. If we have multiple service versions within the package, the pattern we are using will only contain one set of tests and example projects and one readme. 

Optimally we need to version the packages by service version. Instead of a single package for all versions of conversation

> IBM.WatsonDeveloperCloud.Conversation
> IBM.WatsonDeveloperCloud.Conversation.Models
> IBM.WatsonDeveloperCloud.Conversation.Examples
> IBM.WatsonDeveloperCloud.Conversation.UnitTests
> IBM.WatsonDeveloperCloud.Conversation.IntegrationTests

We should have

> IBM.WatsonDeveloperCloud.Conversation.V1
> IBM.WatsonDeveloperCloud.Conversation.V1.Models
> IBM.WatsonDeveloperCloud.Conversation.V1.Examples
> IBM.WatsonDeveloperCloud.Conversation.V1.UnitTests
> IBM.WatsonDeveloperCloud.Conversation.V1.IntegrationTests

> IBM.WatsonDeveloperCloud.Conversation.V2
> IBM.WatsonDeveloperCloud.Conversation.V2.Models
> IBM.WatsonDeveloperCloud.Conversation.V2.Examples
> IBM.WatsonDeveloperCloud.Conversation.V2.UnitTests
> IBM.WatsonDeveloperCloud.Conversation.V2.IntegrationTests

In doing this we can separate the services by version and not worry about having a single set of tests, examples, readme, etc for each service version. We will also be able to easily retire the package as lower versions are deprecated.

---
**Acceptance Criteria:** 

 - [ ] Add a version to the end of each service and datamodel namespace
 - [ ] Redeploy each package to NuGet
 - [ ] Remove all packages without  versioned namespace.

**Comment by atilatosta** [comment]
@mediumTaj I thin that it is the best way. The refactor will be hard, but it is better.

**Comment by mediumTaj** [comment]
OK Let's coordinate with Maykon to find a good time to do this. We will need to merge in all outstanding branches so this doesn't get messy.

**Comment by mediumTaj** [comment]
Complete
