### ISSUE TITLE
[dotnet-standard-sdk] Use named parameters instead of builder pattern

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/dotnet-standard-sdk#78]
## _As a_ developer, _I want_ to use named parameters when using a service, _so that_ i can more easily automatically generate service abstractions.

**Context:**

Currently in the .NET Standard SDK some services are consumed using a builder pattern. For example for PersonalityInsights

```
 // profile
 var results = _personalityInsights.GetProfile(ProfileOptions.CreateOptions()
                                                             .WithTextPlain()
                                                             .AsEnglish()
                                                             .AcceptJson()
                                                             .AcceptEnglishLanguage()
                                                             .WithBody("some text"));
```

We find developers use named variables more often. Creating a builder pattern for each service is very time consuming and is not suitable for automatically generated SDKs. We also have no need to create immutable objects for the call - the higher priority is getting as close to automatically generating an SDK as possible.

```
// profile - using default args of "text/plain", "en", "application/json"
var results = _personalityInsights.GetProfile("some text");
```

---
**Acceptance Criteria:** 

 - [ ] Remove builder pattern from service calls.
 - [ ] Create overload methods to easily call each service endpoint.

**Comment by atilatosta** [comment]
@mediumTaj we decided to use the builder pattern because is being used in the Java SDK and because exists some methods that have many arguments. I think that the builder is more clean and easy. The Recognize method of STT, for example, can have up to 15 arguments. What do you think?

**Comment by mediumTaj** [comment]
@atilatosta I think they want to use something that will be easy to automate using SwaggerCodeGen. We are trying to minimize how much work we need to do when new services are released and German and Jeff think the builder pattern would not be compatible with automatic generation. I think its ok that its in there now since we are still able to pass in the object but the services will be inconsistent as we start generating services.

**Comment by germanattanasio** [comment]
@atilatosta I'm using the builder pattern in Java because I don't have name parameters. Since I'm forced to use positional parameters I decided to use a builder pattern.

In this case, we can use [named and optional parameters](https://msdn.microsoft.com/en-us/library/dd264739.aspx). We do this in python and node already. 

Using named parameter we can do something like this:
```
personalityInsights.profile(text: myText, accept: Spanish, output: CSV);
```

Thoughts ?

**Comment by atilatosta** [comment]
@germanattanasio  It's ok! I just talked to @mediumTaj because I'm worried about the methods where we'll have many parameters, like Recognize for example. But @mediumTaj suggested we create overloads.
