### ISSUE TITLE
[dotnet-standard-sdk] Research automatic SDK generation

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/dotnet-standard-sdk#80]
## _As a_ SDK Developer, _I want_ automatic SDK generation, _so that_ I can speed up SDK development.

There are tools that automatically generate SDKs from Swagger documentation. We need to research these tools to speed up generation of service abstractions and data models. This will be useful even if we are only able to copy and paste generated code.

---
**Acceptance Criteria:** 

 - [ ] Research automatic SDK Generation using documentation.
 - [ ] Test creation of SDK.

**Comment by mediumTaj** [comment]
We cannot generate a .NET Standard SDK using Swagger Codegen. It introduces dependencies to libraries not compatible with .NET Standard. I will try with [AutoREST](https://github.com/Azure/AutoRest)

**Comment by atilatosta** [comment]
@mediumTaj i did it with the Autorest but some abstractions are giving error. The models it's generating right.

**Comment by mediumTaj** [comment]
I will give it a shot today
