### ISSUE TITLE
[conversation] Dynamic Input and Context in Conversation Request

### ISSUE THREAD

**Issue by psbds** [watson-developer-cloud/dotnet-standard-sdk#85]
Hi guys, 

Shouldn't '**Input**' and '**Context**' in '**MessageRequest**' be **dynamic** so the user can send more data to Conversation Service other than just text?

Here are a few examples that we use here in Watson Delivery LA:
- The orchestrator puts a variable in the context indicating the channel (web,mobile,facebook,telegram) and change the dialog based on this variable
    ![image](https://cloud.githubusercontent.com/assets/8377624/24318853/70513c04-10eb-11e7-933f-0170bca9c1b8.png)

- Send the results of tone analyzer in the input, so we can change the dialog accordly as well

    ![image](https://cloud.githubusercontent.com/assets/8377624/24318829/f38c1f40-10ea-11e7-9bc7-0abad81d5f3d.png)

**Comment by atilatosta** [comment]
Hi @psbds! Thanks for your feedback. Yes, I think it's a great feature. We did this in MessageResponse. Let's develop this feature in MessageRequest as well.

**Comment by mediumTaj** [comment]
This fix was overwritten via codegen. Revise codegen to support dynamic

**Comment by mediumTaj** [comment]
A fix of this was handwritten for the `1.2.0` release. This will still need to be implemented into codegen.

**Comment by mediumTaj** [comment]
This is complete in the 3.0 release
