### ISSUE TITLE
Add Xamarin support

### ISSUE THREAD

**Issue by Daiki-Kawanuma** [watson-developer-cloud/dotnet-standard-sdk#91]
This SDK cannot be used on Xamarin projects due to "Microsoft.AspNet.WebApi.Client" package.

Package Microsoft.AspNet.WebApi.Client 5.2.3 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Microsoft.AspNet.WebApi.Client 5.2.3 supports: - net45 (.NETFramework,Version=v4.5) - portable-net45+netcore45+wp8+wp81+wpa81

As described above, Microsoft.AspNet.WebApi.Client doesn't support MonoAndroid+MonoTouch+Xamarin.ios10.

Is it possible to support Xamarin?

**Comment by mediumTaj** [comment]
@atilatosta Have you tested this?

**Comment by Daiki-Kawanuma** [comment]
Sorry for the late reply.

I tried to add this SDK package to Xamarin .NET Standard PCL project but it failed.
The following is NuGet package install error.

Restoring packages for 'WatsonSample'.
Restoring packages for /Users/DaikiKawanuma/Projects/WatsonSample/WatsonSample/project.json...
Restoring packages for .NETStandard,Version=v1.6.2...
Resolving conflicts for .NETStandard,Version=v1.6.2...
Checking compatibility of packages on .NETStandard,Version=v1.6.2.
Checking compatibility for WatsonSample 1.0.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for IBM.WatsonDeveloperCloud.Conversation 0.1.1-alpha with .NETStandard,Version=v1.6.2.
Checking compatibility for Microsoft.NETCore.Portable.Compatibility 1.0.1 with .NETStandard,Version=v1.6.2.
Checking compatibility for NETStandard.Library 1.6.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.ComponentModel 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Runtime.Serialization.Json 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for Xam.Plugins.Forms.RoundedBoxView 1.0.0.7 with .NETStandard,Version=v1.6.2.
Checking compatibility for Xamarin.Forms 2.3.4.231 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Runtime.Serialization.Xml 4.1.1 with .NETStandard,Version=v1.6.2.
Checking compatibility for IBM.WatsonDeveloperCloud 0.1.1-alpha with .NETStandard,Version=v1.6.2.
Checking compatibility for Microsoft.AspNet.WebApi.Client 5.2.3 with .NETStandard,Version=v1.6.2.
Package Microsoft.AspNet.WebApi.Client 5.2.3 is not compatible with netstandard1.6.2 (.NETStandard,Version=v1.6.2). Package Microsoft.AspNet.WebApi.Client 5.2.3 supports:
  - net45 (.NETFramework,Version=v4.5)
  - portable-net45+netcore45+wp8+wp81+wpa81 (.NETPortable,Version=v0.0,Profile=wp8+netcore45+net45+wp81+wpa81)
Checking compatibility for Newtonsoft.Json 9.0.1 with .NETStandard,Version=v1.6.2.
Checking compatibility for Microsoft.NETCore.Runtime.CoreCLR 1.0.2 with .NETStandard,Version=v1.6.2.
Checking compatibility for Microsoft.Win32.Primitives 4.0.1 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.AppContext 4.1.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Console 4.0.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Globalization.Calendars 4.0.1 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.IO.Compression 4.1.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.IO.Compression.ZipFile 4.0.1 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Linq.Expressions 4.1.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Net.Http 4.1.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Net.Primitives 4.0.11 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Net.Sockets 4.1.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.ObjectModel 4.0.12 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Runtime.InteropServices.RuntimeInformation 4.0.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Runtime.Numerics 4.0.1 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Security.Cryptography.Algorithms 4.2.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Security.Cryptography.Encoding 4.0.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Security.Cryptography.Primitives 4.0.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Security.Cryptography.X509Certificates 4.1.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Threading.Timer 4.0.1 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Runtime 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.IO 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Private.DataContractSerialization 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for Microsoft.CSharp 4.0.1 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Dynamic.Runtime 4.0.11 with .NETStandard,Version=v1.6.2.
Checking compatibility for Microsoft.NETCore.Jit 1.0.2 with .NETStandard,Version=v1.6.2.
Checking compatibility for Microsoft.NETCore.Windows.ApiSets 1.0.1 with .NETStandard,Version=v1.6.2.
Checking compatibility for runtime.native.System 4.0.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for runtime.native.System.IO.Compression 4.1.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Buffers 4.0.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for runtime.native.System.Net.Http 4.0.1 with .NETStandard,Version=v1.6.2.
Checking compatibility for runtime.native.System.Security.Cryptography 4.0.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Diagnostics.DiagnosticSource 4.0.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Globalization.Extensions 4.0.1 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Security.Cryptography.OpenSsl 4.0.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Security.Cryptography.Cng 4.2.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Security.Cryptography.Csp 4.0.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for Microsoft.NETCore.Platforms 1.1.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for Microsoft.NETCore.Targets 1.1.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Text.Encoding 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Threading.Tasks 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Collections 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Collections.Concurrent 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Diagnostics.Debug 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Globalization 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Linq 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Reflection 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Reflection.Emit.ILGeneration 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Reflection.Emit.Lightweight 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Reflection.Extensions 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Reflection.Primitives 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Reflection.TypeExtensions 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Resources.ResourceManager 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Runtime.Extensions 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Runtime.Serialization.Primitives 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Text.Encoding.Extensions 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Text.RegularExpressions 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Threading 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Xml.ReaderWriter 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Xml.XDocument 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Xml.XmlDocument 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Xml.XmlSerializer 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Diagnostics.Tracing 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.IO.FileSystem 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.IO.FileSystem.Primitives 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Runtime.InteropServices 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Threading.Tasks.Extensions 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Diagnostics.Tools 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Reflection.Emit 4.3.0 with .NETStandard,Version=v1.6.2.
Checking compatibility for System.Runtime.Handles 4.3.0 with .NETStandard,Version=v1.6.2.
One or more packages are incompatible with .NETStandard,Version=v1.6.2.
Incompatible packages: 1
Package restore failed for 'WatsonSample'.
Writing lock file to disk. Path: /Users/DaikiKawanuma/Projects/WatsonSample/WatsonSample/project.lock.json
Generating MSBuild file WatsonSample.nuget.targets.
Restore failed.


And project.json here.

`{
  "supports": {},
  "dependencies": {
    "IBM.WatsonDeveloperCloud.Conversation": "0.1.1-alpha",
    "Microsoft.NETCore.Portable.Compatibility": "1.0.1",
    "NETStandard.Library": "1.6",
    "System.ComponentModel": "4.3.0",
    "System.Runtime.Serialization.Json": "4.3.0",
    "Xam.Plugins.Forms.RoundedBoxView": "1.0.0.7",
    "Xamarin.Forms": "2.3.4.231"
  },
  "frameworks": {
    "netstandard1.6.2": {
      "imports": "portable-net46+monoandroid10+xamarinios10+"
    }
  }
}`

**Comment by atilatosta** [comment]
@Daiki-Kawanuma hi! We believe that support is possible. We're working on it.

@mediumTaj We are doing some implementations and testing to try to make this possible

**Comment by jefftmahoney** [comment]
I would really love to see Xamarin supported.  I'm running it on a Mac and have tried targeting my solution to every .NET framework version in the list, and no luck.  The error I get makes it sound like the problem is the framework version I'm targeting, but the thread above seems to indicate deeper problems.  Anyway, would love to have this if you can make it happen!
